services:
  flask:
    image: aaronw/flasktest:latest
    container_name: flask_app
    networks:
      - app-network

  grpc:
    image: aaronw/grpctest:latest
    container_name: grpc_app
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:v1.23-latest
    container_name: envoy_proxy
    ports:
      - "8080:8080" 
      - "8081:8081"
      - "9901:9901"  # admin
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml  # Envoy configuration file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

      
