services:
  flask:
    image: aaronw/flasktest:latest
    container_name: flask_app
    depends_on:
      envoy:
        condition: service_started
    networks:
      - app-network


  grpc:
    image: aaronw/grpctest:latest
    container_name: grpc_app
    depends_on:
      envoy:
        condition: service_started
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:dev-4aa1d1b2b7bc408d5b61ee2eb389e31300b76ad0 # 1.33-dev build
    container_name: envoy_proxy
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9901:9901"  # admin
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml  # Envoy configuration file
    networks:
      - app-network
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "--component-log-level main:warn"

networks:
  app-network:
    driver: bridge
