services:
  flask:
    image: aaronw/flasktest
    container_name: flask_app
#    ports:
#      - "5000:5000"  # Exposes Flask app on port 5000
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:v1.23-latest
    container_name: envoy_proxy
    ports:
      - "8080:8080"  # Exposes Envoy proxy on port 10000
      - "9901:9901"  # Exposes Envoy admin on port 9901
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml  # Envoy configuration file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

      
