apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ingress
  namespace: teamwald
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: teamwald.local
    http:
      paths:
      - path: /static(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: rook
            port:
              number: 9090
