apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-pv
  namespace: teamwald
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/rook
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-pvc
  namespace: teamwald
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual