apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rook
  name: rook
spec:
  ports:
    - name: "ws"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: rook
