version: '3'

services:
  envoy:
    image: envoyproxy/envoy:v1.18.3
    ports:
      - "9901:9901" # Admin port
      - "10000:10000" # Service port
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  flasktest:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      # Forwards the local Docker socket to the container.      version: '3'
      
      services:
        envoy:
          image: envoyproxy/envoy:v1.18.3
          ports:
            - "9901:9901" # Admin port
            - "10000:10000" # Service port
          volumes:
            - ./envoy.yaml:/etc/envoy/envoy.yaml
      
        flasktest:
          image: aaronw/flasktest
      
          volumes:
            # Forwards the local Docker socket to the container.
            - /var/run/docker.sock:/var/run/docker-host.sock 
            # Update this to wherever you want VS Code to mount the folder of your project
            - ../..:/workspaces:cached
      
          # Overrides default command so things don't shut down after the process ends.
          entrypoint: /usr/local/share/docker-init.sh
          command: sleep infinity 
      
          depends_on:
            - envoy
      
